// Generated by continue

import type { DiffLine, ILLM } from "../index";
import { gptEditPrompt } from "../llm/templates/edit";
import { defaultApplyPrompt } from "../llm/templates/edit/gpt";
import {
  LINE_PATCH_MARKER_KEY,
  looksLikeContinueLinePatchJson,
} from "./lazy/lineRangePatch";
import { addIndentation, streamDiffLines } from "./streamDiffLines";

describe("addIndentation", () => {
  async function* mockDiffLineGenerator(lines: DiffLine[]) {
    for (const line of lines) {
      yield line;
    }
  }

  test("should add indentation to each line", async () => {
    const lines: DiffLine[] = [
      { type: "same", line: "Line 1" },
      { type: "new", line: "Line 2" },
      { type: "old", line: "Line 3" },
    ];
    const indentation = "  ";

    const generator = addIndentation(mockDiffLineGenerator(lines), indentation);

    const result: DiffLine[] = [];
    for await (const diffLine of generator) {
      result.push(diffLine);
    }

    expect(result).toEqual([
      { type: "same", line: "  Line 1" },
      { type: "new", line: "  Line 2" },
      { type: "old", line: "  Line 3" },
    ]);
  });

  test("should handle empty generator", async () => {
    const lines: DiffLine[] = [];
    const indentation = "\t";

    const generator = addIndentation(mockDiffLineGenerator(lines), indentation);

    const result: DiffLine[] = [];
    for await (const diffLine of generator) {
      result.push(diffLine);
    }

    expect(result).toEqual([]);
  });

  test("should handle no indentation", async () => {
    const lines: DiffLine[] = [{ type: "same", line: "Line 1" }];
    const indentation = "";

    const generator = addIndentation(mockDiffLineGenerator(lines), indentation);

    const result: DiffLine[] = [];
    for await (const diffLine of generator) {
      result.push(diffLine);
    }

    expect(result).toEqual([{ type: "same", line: "Line 1" }]);
  });

  test("should propagate errors from the source generator", async () => {
    async function* errorGenerator(): AsyncGenerator<DiffLine> {
      throw new Error("Test error");
    }
    const indentation = "  ";

    const generator = addIndentation(errorGenerator(), indentation);

    await expect(async () => {
      for await (const _ of generator) {
        // Consume the generator
      }
    }).rejects.toThrow("Test error");
  });
});

describe("streamDiffLines apply + continue-line-patch", () => {
  function collectDiffs(gen: AsyncGenerator<DiffLine>): Promise<DiffLine[]> {
    const out: DiffLine[] = [];
    return (async () => {
      for await (const d of gen) {
        out.push(d);
      }
      return out;
    })();
  }

  it("uses JSON patch from merge completion", async () => {
    const highlighted = "line1\nline2\nline3";
    const patch = JSON.stringify({
      [LINE_PATCH_MARKER_KEY]: 1,
      replacements: [{ startLine: 2, endLine: 2, lines: ["LINE2"] }],
    });

    const llm = {
      model: "gpt-4",
      providerName: "openai",
      completionOptions: {},
      promptTemplates: {},
      renderPromptTemplate: (tpl: unknown, history: unknown, data: unknown) =>
        (typeof tpl === "function" ? tpl : defaultApplyPrompt)(
          history,
          data,
        ),
      async *streamChat() {
        yield { role: "assistant", content: patch };
      },
    } as unknown as ILLM;

    const diffs = await collectDiffs(
      streamDiffLines(
        {
          type: "apply",
          prefix: "",
          highlighted,
          suffix: "",
          input: "",
          language: "typescript",
          newCode: "hint",
          includeRulesInSystemMessage: false,
          modelTitle: "test",
        },
        llm,
        new AbortController(),
        undefined,
        undefined,
      ),
    );

    expect(diffs.some((x) => x.type === "old" && x.line === "line2")).toBe(true);
    expect(diffs.some((x) => x.type === "new" && x.line === "LINE2")).toBe(
      true,
    );
  });

  it("accepts fenced JSON patch", async () => {
    const highlighted = "a\nb";
    const inner = JSON.stringify({
      [LINE_PATCH_MARKER_KEY]: 1,
      replacements: [{ startLine: 1, endLine: 1, lines: ["A"] }],
    });
    const llm = {
      model: "gpt-4",
      providerName: "openai",
      completionOptions: {},
      promptTemplates: {},
      renderPromptTemplate: (tpl: unknown, history: unknown, data: unknown) =>
        (typeof tpl === "function" ? tpl : defaultApplyPrompt)(
          history,
          data,
        ),
      async *streamChat() {
        yield {
          role: "assistant",
          content: "```json\n" + inner + "\n```",
        };
      },
    } as unknown as ILLM;

    const diffs = await collectDiffs(
      streamDiffLines(
        {
          type: "apply",
          prefix: "",
          highlighted,
          suffix: "",
          input: "",
          language: "typescript",
          newCode: "",
          includeRulesInSystemMessage: false,
          modelTitle: "test",
        },
        llm,
        new AbortController(),
        undefined,
        undefined,
      ),
    );

    expect(diffs.some((x) => x.type === "new" && x.line === "A")).toBe(true);
  });

  it("merge rejects invalid patch-shaped JSON instead of treating as code", async () => {
    const bad = `{"${LINE_PATCH_MARKER_KEY}":1,`;
    expect(looksLikeContinueLinePatchJson(bad)).toBe(true);

    const llm = {
      model: "gpt-4",
      providerName: "openai",
      completionOptions: {},
      promptTemplates: {},
      renderPromptTemplate: (tpl: unknown, history: unknown, data: unknown) =>
        (typeof tpl === "function" ? tpl : defaultApplyPrompt)(
          history,
          data,
        ),
      async *streamChat() {
        yield { role: "assistant", content: bad };
      },
    } as unknown as ILLM;

    await expect(
      collectDiffs(
        streamDiffLines(
          {
            type: "apply",
            prefix: "",
            highlighted: "a\nb",
            suffix: "",
            input: "",
            language: "typescript",
            newCode: "",
            includeRulesInSystemMessage: false,
            modelTitle: "test",
          },
          llm,
          new AbortController(),
          undefined,
          undefined,
        ),
      ),
    ).rejects.toThrow(/invalid or incomplete/i);
  });

  it("edit merge uses continue-line-patch the same as apply", async () => {
    const highlighted = "one\ntwo\nthree";
    const patch = JSON.stringify({
      [LINE_PATCH_MARKER_KEY]: 1,
      replacements: [{ startLine: 2, endLine: 2, lines: ["TWO"] }],
    });

    const llm = {
      model: "gpt-4",
      providerName: "openai",
      completionOptions: {},
      promptTemplates: {},
      renderPromptTemplate: (tpl: unknown, history: unknown, data: unknown) =>
        (typeof tpl === "function" ? tpl : gptEditPrompt)(history, data),
      async *streamComplete() {
        yield patch;
      },
      async *streamChat() {
        yield { role: "assistant", content: patch };
      },
    } as unknown as ILLM;

    const diffs = await collectDiffs(
      streamDiffLines(
        {
          type: "edit",
          prefix: "",
          highlighted,
          suffix: "",
          input: "change line 2",
          language: "typescript",
          includeRulesInSystemMessage: false,
          modelTitle: "test",
        },
        llm,
        new AbortController(),
        undefined,
        undefined,
      ),
    );

    expect(diffs.some((x) => x.type === "old" && x.line === "two")).toBe(true);
    expect(diffs.some((x) => x.type === "new" && x.line === "TWO")).toBe(true);
  });
});
